<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Parth" ignored="0" name="Bank Test" tests="5" failures="1" timestamp="2023-07-16T15:14:19 BST" time="48.949" errors="0">
  <testcase name="bankManagerShouldAddCustomerSuccessfully" time="6.015" classname="com.bank.testsuite.BankTest"/>
  <testcase name="bankManagerShouldOpenAccountSuccessfully" time="6.001" classname="com.bank.testsuite.BankTest"/>
  <testcase name="customerShouldDepositMoneySuccessfully" time="7.005" classname="com.bank.testsuite.BankTest"/>
  <testcase name="customerShouldLoginAndLogoutSuceessfully" time="5.939" classname="com.bank.testsuite.BankTest"/>
  <testcase name="customerShouldWithdrawMoneySuccessfully" time="6.033" classname="com.bank.testsuite.BankTest">
    <failure type="java.lang.AssertionError" message="Transaction Successful is not displayed expected [Transaction Successful] but found [Transaction Failed. You can not withdraw amount more than the balance.]">
      <![CDATA[java.lang.AssertionError: Transaction Successful is not displayed expected [Transaction Successful] but found [Transaction Failed. You can not withdraw amount more than the balance.]
at com.bank.testsuite.BankTest.customerShouldWithdrawMoneySuccessfully(BankTest.java:175)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- customerShouldWithdrawMoneySuccessfully -->
</testsuite> <!-- Bank Test -->
